# Generated by Django 2.1 on 2019-04-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Media'),
        ),
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaAuthor'),
        ),
    ]
